import React, { useState } from 'react';
import { Modal, Pressable, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useLibrary, id } from '../src/state/Library';
import { usePlayback } from '../src/state/Playback';
import { Playlist, move } from '../src/core/model';
import { Shell } from '../src/ui/Shell';
import { Artwork, Button, Empty } from '../src/ui/kit';
import { TrackRow } from '../src/ui/LibraryScreen';
import { c, styles } from '../src/ui/theme';
export default function Playlists() {
  const { id: selectedId } = useLocalSearchParams<{ id?: string }>(); const { state, savePlaylist } = useLibrary(); const p = usePlayback();
  const [selected, setSelected] = useState<string | undefined>(selectedId); const [editing, setEditing] = useState<Playlist | null>(null); const [name, setName] = useState(''); const [remove, setRemove] = useState(false); const [adding, setAdding] = useState(false);
  const list = state.playlists.filter(p => !p.deleted); const playlist = list.find(p => p.id === selected);
  function edit(value?: Playlist) { const next = value || { id: id(), name: '', trackIds: [], updatedAt: Date.now() }; setEditing(next); setName(next.name); }
  return <Shell><View style={styles.section}><View style={[styles.row, { justifyContent: 'space-between', flexWrap: 'wrap' }]}><View><Text style={styles.title}>Made by you.</Text><Text style={styles.subtitle}>A collection for every detour.</Text></View><Button primary icon="add" onPress={() => edit()}>New playlist</Button></View><View style={styles.wrap}>{list.map(v => <Pressable key={v.id} accessibilityRole="button" onPress={() => setSelected(v.id)} style={[styles.card, { width: 180, borderColor: selected === v.id ? c.accent : c.border }]}><Artwork track={state.tracks.find(t => t.id === v.trackIds[0])} size={134} /><Text numberOfLines={1} style={{ color: c.text, fontWeight: '600' }}>{v.name}</Text><Text style={styles.subtitle}>{v.trackIds.length} tracks</Text></Pressable>)}</View>{!list.length && <Empty title="Every good trip needs a playlist" description="Create a collection, add your local tracks, and put them in just the right order." action={<Button primary onPress={() => edit()}>Create a playlist</Button>} />}</View>
    {playlist && <View style={styles.section}><View style={[styles.row, { justifyContent: 'space-between', flexWrap: 'wrap' }]}><Text style={{ color: c.text, fontSize: 26 }}>{playlist.name}</Text><View style={styles.wrap}><Button icon="play" onPress={() => { void p.play(playlist.trackIds); }}>Play</Button><Button icon="shuffle" onPress={() => { void p.play(playlist.trackIds, 0, true); }}>Shuffle</Button><Button icon="add" onPress={() => setAdding(!adding)}>Add tracks</Button><Button icon="pencil-outline" onPress={() => edit(playlist)}>Rename</Button><Button icon="trash-outline" label="Delete playlist" onPress={() => setRemove(true)} /></View></View>
      {adding && <View style={styles.card}><Text style={styles.label}>Add from your library</Text>{state.tracks.filter(t => !playlist.trackIds.includes(t.id)).map(t => <Button key={t.id} icon="add" onPress={() => savePlaylist({ ...playlist, trackIds: [...playlist.trackIds, t.id] })}>{t.title}</Button>)}{!state.tracks.length && <Text style={styles.subtitle}>Import tracks to your library first.</Text>}</View>}
      {playlist.trackIds.map((key, i) => { const track = state.tracks.find(t => t.id === key); return <View key={`${key}-${i}`}><View style={{ flex: 1 }}>{track ? <TrackRow track={track} index={i} onPlay={() => { void p.play(playlist.trackIds, i); }} /> : <Text style={styles.subtitle}>Missing metadata · {key}</Text>}</View><View style={[styles.row, { justifyContent: 'flex-end', marginTop: 6, marginBottom: 6 }]}><Button compact icon="arrow-up" label={`Move track ${i + 1} up`} disabled={i === 0} onPress={() => savePlaylist({ ...playlist, trackIds: move(playlist.trackIds, i, i - 1) })} /><Button compact icon="arrow-down" label={`Move track ${i + 1} down`} disabled={i === playlist.trackIds.length - 1} onPress={() => savePlaylist({ ...playlist, trackIds: move(playlist.trackIds, i, i + 1) })} /><Button compact icon="remove" label={`Remove track ${i + 1} from playlist`} onPress={() => savePlaylist({ ...playlist, trackIds: playlist.trackIds.filter((_, n) => n !== i) })} /></View></View>; })}
      {!playlist.trackIds.length && <Empty title="A blank canvas for your next mix" description="Add tracks from your library to start this playlist." />}
    </View>}
    <Modal transparent visible={!!editing} onRequestClose={() => setEditing(null)}><View style={{ flex: 1, backgroundColor: '#000000aa', alignItems: 'center', justifyContent: 'center', padding: 24 }}><View style={[styles.card, { width: '100%', maxWidth: 420 }]}><Text style={{ color: c.text, fontSize: 24 }}>Name your collection</Text><TextInput autoFocus accessibilityLabel="Playlist name" placeholder="The long way home" placeholderTextColor={c.muted} style={styles.input} value={name} maxLength={120} onChangeText={setName} /><Button primary disabled={!name.trim()} onPress={() => { if (editing && name.trim()) { savePlaylist({ ...editing, name: name.trim() }); setSelected(editing.id); setEditing(null); } }}>Save playlist</Button><Button onPress={() => setEditing(null)}>Cancel</Button></View></View></Modal>
    <Modal transparent visible={remove} onRequestClose={() => setRemove(false)}><View style={{ flex: 1, backgroundColor: '#000000aa', alignItems: 'center', justifyContent: 'center', padding: 24 }}><View style={[styles.card, { maxWidth: 420 }]}><Text style={{ color: c.text, fontSize: 22 }}>Delete this playlist?</Text><Text style={styles.subtitle}>Your tracks stay in the library. This playlist deletion will sync to signed-in devices.</Text><Button primary onPress={() => { if (playlist) savePlaylist({ ...playlist, deleted: true }); setRemove(false); setSelected(undefined); }}>Delete playlist</Button><Button onPress={() => setRemove(false)}>Keep playlist</Button></View></View></Modal>
  </Shell>;
}
