import React from 'react';
import { Platform, Switch, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useLibrary, change } from '../src/state/Library';
import { Shell } from '../src/ui/Shell';
import { Button } from '../src/ui/kit';
import { styles } from '../src/ui/theme';
export default function Settings() {
  const { state, update } = useLibrary(); const router = useRouter();
  return <Shell><View style={styles.section}><Text style={styles.title}>A space that feels like you.</Text><Text style={styles.subtitle}>Playback, privacy, and the small details.</Text><View style={styles.card}><View style={[styles.row, { justifyContent: 'space-between' }]}><Text style={styles.subtitle}>Reduce motion</Text><Switch accessibilityLabel="Reduce motion" value={state.settings.reducedMotion} onValueChange={value => update(s => ({ ...s, settings: { ...s.settings, reducedMotion: value }, outbox: [...s.outbox, change('settings', 'preferences', { reducedMotion: value })] }))} /></View><Text style={styles.subtitle}>SoundTrip also respects your system’s reduced-motion preference.</Text><Button onPress={() => update(s => ({ ...s, settings: { ...s.settings, onboarded: false } }))}>Show introduction again</Button></View><View style={styles.card}><Text style={styles.label}>On this platform</Text><Text style={styles.subtitle}>{Platform.OS === 'web' ? 'Imported files live in IndexedDB in this browser, on this origin. Clearing site data, private browsing, or storage eviction can remove files and playlists. Install and open the production web app once online for its offline app shell. Background audio and media controls vary by browser and OS.' : 'Files selected through the system picker are copied to app-owned documents. Playback does not need the network. Background audio and lock-screen controls require a native development or production build. Headphone disconnection and interruptions are handled by the native audio session.'}</Text><Text style={styles.subtitle}>Codec support differs by device. MP3 and PCM WAV are good starting points. SoundTrip reads ID3v2.3/2.4 title, artist, album, artwork and embedded lyrics, WAV duration, and FLAC comments. Other files use their filenames until you edit details; playback fills duration.</Text></View><View style={styles.card}><Text style={styles.label}>Private by default</Text><Text style={styles.subtitle}>Local audio, artwork, and lyrics stay on this device. Sign-in is optional. Metadata sync shares titles, artists, albums, file fingerprints, favorites, moods, playlists, and your motion preference. It does not transfer audio or file paths.</Text><Text style={styles.subtitle}>To listen on another device, explicitly transfer original files you own using your operating system or an authorized storage service, then import them there. Matching file fingerprints reconnect your synced library.</Text><Text style={styles.subtitle}>No lyric websites are scraped. External lyrics are disabled until a licensed provider and credentials are configured.</Text><Button icon="person-outline" onPress={() => router.push('/account')}>Account & data controls</Button><Button icon="link-outline" onPress={() => router.push('/spotify')}>Spotify connection & disconnect</Button></View></View></Shell>;
}
